import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, Banknote, CheckCircle2, ChevronDown, CircleDollarSign, CloudCog, Download, FileArchive, LayoutDashboard, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Users } from 'lucide-react';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';

type View = 'overview' | 'members' | 'contributions' | 'sepa' | 'spg' | 'settings';
type MemberInput = {
  memberNumber?: string; salutation?: string; title?: string; firstName: string; lastName: string;
  gender?: string; birthDate?: string; street?: string; postalCode?: string; city?: string; country?: string;
  phonePrivate?: string; phoneMobile?: string; phoneBusiness?: string; email?: string; website?: string;
  entryDate: string; exitDate?: string; exitReason?: string; department?: string; departmentEntryDate?: string;
  contributionType?: string; annualFeeCents: number; paymentFrequency?: string; paymentMethod?: string;
  accountHolder?: string; iban?: string; bic?: string; mandateReference?: string; mandateSignedAt?: string;
  sepaSequence?: string; functionName?: string; honors?: string; alternateAddress?: string; customFields?: string | Record<string, string>;
  notes?: string; privacyConsentAt?: string; imageConsent?: boolean; emailConsent?: boolean;
};
type Member = MemberInput & { id: string; memberNumber: string; spgSyncedAt?: string | null };
type BridgeStatus = { connected: boolean; compatible: boolean; writeCompatible?: boolean; sqlServerMajor?: number; databaseVersion?: number; mandant?: string; reason?: string | null };

const contributionTypes = [
  { code: '01', name: 'Erwachsene aktive Mitglieder', amount: 8000 },
  { code: '02', name: 'Inaktive/fördernde Mitglieder', amount: 1500 },
  { code: '03', name: 'Jugendliche bis 17 Jahren', amount: 6000 },
  { code: '04', name: 'Familienmitgliedschaft', amount: 4000 },
];

export default function App() {
  const [view, setView] = useState<View>('members');
  const [members, setMembers] = useState<Member[]>([]);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const reload = useCallback(async () => {
    try {
      const response = await fetch('/api/members');
      const data = (await response.json()) as { members?: Member[]; error?: string };
      if (!response.ok) throw new Error(data.error || 'Bestand konnte nicht geladen werden.');
      setMembers(data.members || []);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Bestand konnte nicht geladen werden.'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void reload(); }, [reload]);
  async function saveMember(input: MemberInput, id?: string) {
    const response = await fetch(id ? `/api/members/${id}` : '/api/members', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) });
    const data = (await response.json()) as { member?: Member; error?: string };
    if (!response.ok || !data.member) throw new Error(data.error || 'Das Mitglied konnte nicht gespeichert werden.');
    setMembers((current) => id ? current.map((member) => member.id === id ? data.member! : member) : [...current, data.member!]);
    setNotice(`${input.firstName} ${input.lastName} wurde gespeichert.`); setError(''); setView('members');
    return data.member;
  }
  return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)]">
    <Sidebar view={view} setView={setView} />
    <main className="lg:pl-[260px]"><header className="flex min-h-16 items-center justify-between border-b border-black/6 bg-white/85 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-2 text-sm text-[var(--muted-ink)]"><ShieldCheck className="size-4 text-[var(--teal)]" />Private Vereinsverwaltung</div><Badge variant="outline" className="border-[var(--mint)] bg-[var(--sky)] text-[var(--teal-dark)]">NAS · lokaler Bestand</Badge></header>
      <div className="mx-auto max-w-[1500px] px-5 py-7 md:px-8 md:py-9"><MobileNav view={view} setView={setView} />
        {(notice || error) && <Notice error={error}>{error || notice}</Notice>}
        {view === 'overview' && <Overview members={members} />}
        {view === 'members' && <MembersView members={members} loading={loading} onSave={saveMember} />}
        {view === 'contributions' && <ContributionsView members={members} />}
        {view === 'sepa' && <SepaView members={members} />}
        {view === 'spg' && <SpgView members={members} onImported={reload} />}
        {view === 'settings' && <SettingsView />}
      </div>
    </main>
  </div>;
}

function Sidebar({ view, setView }: { view: View; setView: (view: View) => void }) {
  const items: Array<[View, typeof Users, string]> = [['overview', LayoutDashboard, 'Übersicht'], ['members', Users, 'Mitglieder'], ['contributions', CircleDollarSign, 'Beiträge'], ['sepa', Banknote, 'SEPA-Läufe'], ['spg', FileArchive, 'SPG-Sicherung']];
  return <aside className="fixed inset-y-0 left-0 z-10 hidden w-[260px] flex-col bg-[var(--navy)] px-4 py-5 text-white lg:flex"><div className="flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl bg-[var(--mint)] font-bold text-[var(--navy)]">G</div><div><p className="text-sm font-semibold">GUT Verein</p><p className="text-xs text-white/55">Mitgliederverwaltung</p></div></div><nav className="mt-10 space-y-1" aria-label="Hauptnavigation">{items.map(([key, Icon, label]) => <NavItem key={key} icon={Icon} label={label} active={view === key} onClick={() => setView(key)} />)}</nav><div className="mt-auto space-y-1"><NavItem icon={Settings} label="Einstellungen" active={view === 'settings'} onClick={() => setView('settings')} /><div className="mt-4 flex items-center gap-3 border-t border-white/10 px-2 pt-5"><Avatar className="size-9"><AvatarFallback className="bg-white/10 text-xs text-white">MV</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Vereinsvorstand</p><p className="truncate text-xs text-white/50">Lokal angemeldet</p></div><ChevronDown className="size-4 text-white/50" /></div></div></aside>;
}
function NavItem({ icon: Icon, label, active = false, onClick }: { icon: typeof Users; label: string; active?: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${active ? 'bg-white text-[var(--navy)] shadow-sm' : 'text-white/65 hover:bg-white/7 hover:text-white'}`}><Icon className={`size-[18px] ${active ? 'text-[var(--teal)]' : ''}`} />{label}</button>; }
function MobileNav({ view, setView }: { view: View; setView: (view: View) => void }) { const items: Array<[View, string]> = [['overview', 'Übersicht'], ['members', 'Mitglieder'], ['contributions', 'Beiträge'], ['sepa', 'SEPA'], ['spg', 'SPG'], ['settings', 'Einstellungen']]; return <div className="mb-6 flex gap-2 overflow-x-auto lg:hidden">{items.map(([key, label]) => <Button key={key} size="sm" variant={view === key ? 'default' : 'outline'} onClick={() => setView(key)} className={view === key ? 'bg-[var(--navy)] text-white' : 'bg-white'}>{label}</Button>)}</div>; }

function Overview({ members }: { members: Member[] }) {
  const active = members.filter((member) => !member.exitDate);
  return <><PageTitle eyebrow="ÜBERSICHT" title="Vereinsbestand" description="Mitglieder, Beitragssoll und offene manuelle SPG-Übertragungen auf einen Blick." /><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Mitglieder" value={String(members.length)} detail={`${active.length} aktiv`} accent /><Stat label="SEPA-Mitglieder" value={String(active.filter((m) => m.paymentMethod === 's').length)} detail="mit Lastschrift" /><Stat label="Jahresbeiträge" value={euro(active.reduce((sum, m) => sum + m.annualFeeCents, 0))} detail="aktueller Sollwert" /><Stat label="SPG-Übertrag offen" value={String(members.filter((m) => !m.spgSyncedAt).length)} detail="neu oder geändert" /></section></>;
}

function MembersView({ members, loading, onSave }: { members: Member[]; loading: boolean; onSave: (input: MemberInput, id?: string) => Promise<Member> }) {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => members.filter((member) => `${member.firstName} ${member.lastName} ${member.memberNumber} ${member.email || ''}`.toLowerCase().includes(query.toLowerCase())), [members, query]);
  return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><PageTitle eyebrow="MITGLIEDERBESTAND" title="Mitglieder verwalten" description="Alle SPG-relevanten Felder in acht übersichtlichen Bereichen." /><MemberDialog onSave={onSave} /></div><section className="mt-8 overflow-hidden rounded-2xl border border-black/7 bg-white shadow-[0_12px_40px_rgba(21,43,58,0.045)]"><div className="flex flex-col gap-4 border-b border-black/7 p-4 sm:flex-row sm:items-center sm:justify-between md:p-5"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--muted-ink)]" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 border-black/10 bg-[var(--canvas)] pl-10" placeholder="Name, E-Mail oder Mitgliedsnummer" aria-label="Mitglieder suchen" /></div><Badge variant="outline">{filtered.length} Einträge</Badge></div>
    {!loading && !filtered.length ? <div className="px-6 py-20 text-center"><Users className="mx-auto size-10 text-[var(--teal)]" /><h2 className="mt-4 text-xl font-semibold">Noch keine Mitglieder angelegt</h2><p className="mt-2 text-sm text-[var(--muted-ink)]">Lege den ersten Datensatz an oder verbinde den SPG-Bestand über die Windows-Brücke.</p></div> : <Table><TableHeader><TableRow className="border-black/7 hover:bg-transparent"><TableHead className="pl-5">Mitglied</TableHead><TableHead>Nummer</TableHead><TableHead>Eintritt</TableHead><TableHead>Jahresbeitrag</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Aktionen</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map((member) => <TableRow key={member.id} className="border-black/6"><TableCell className="pl-5"><div className="flex items-center gap-3"><Avatar className="size-9"><AvatarFallback className="bg-[var(--sky)] text-xs font-semibold text-[var(--navy)]">{initials(member)}</AvatarFallback></Avatar><div><p className="font-medium">{member.firstName} {member.lastName}</p><p className="text-sm text-[var(--muted-ink)]">{member.email || 'Keine E-Mail'}</p></div></div></TableCell><TableCell className="font-mono text-sm text-[var(--muted-ink)]">{member.memberNumber}</TableCell><TableCell>{dateDe(member.entryDate)}</TableCell><TableCell>{euro(member.annualFeeCents)}</TableCell><TableCell><Badge variant="outline" className={member.exitDate ? 'border-slate-200 bg-slate-50 text-slate-600' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}>{member.exitDate ? 'Ausgetreten' : 'Aktiv'}</Badge></TableCell><TableCell><MemberDialog member={member} onSave={onSave} trigger={<Button variant="ghost" size="icon" aria-label={`${member.firstName} ${member.lastName} bearbeiten`}><MoreHorizontal className="size-4" /></Button>} /></TableCell></TableRow>)}</TableBody></Table>}
  </section></>;
}

function MemberDialog({ member, onSave, trigger }: { member?: Member; onSave: (input: MemberInput, id?: string) => Promise<Member>; trigger?: React.ReactElement }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); try { await onSave(memberInput(new FormData(event.currentTarget)), member?.id); setOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Speichern fehlgeschlagen.'); } finally { setSaving(false); } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={trigger || <Button className="h-11 bg-[var(--teal)] px-5 text-white hover:bg-[var(--teal-dark)]" />}>{trigger ? null : <><Plus className="mr-2 size-4" />Neues Mitglied</>}</DialogTrigger><DialogContent className="max-h-[94vh] overflow-y-auto sm:max-w-[980px]"><DialogHeader><DialogTitle>{member ? `${member.firstName} ${member.lastName}` : 'Neues Mitglied'}</DialogTitle><DialogDescription>Die Bereiche entsprechen dem vollständigen SPG-Mitgliedsdatensatz. Änderungen werden für die nächste SPG-Sicherung vorgemerkt.</DialogDescription></DialogHeader><form onSubmit={submit}>{error && <div className="mb-4 flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="size-4" />{error}</div>}<Tabs defaultValue="base"><TabsList variant="line" className="w-full justify-start overflow-x-auto border-b pb-2"><TabsTrigger value="base">Stammdaten</TabsTrigger><TabsTrigger value="contact">Kommunikation</TabsTrigger><TabsTrigger value="bank">Bank & SEPA</TabsTrigger><TabsTrigger value="fees">Abteilungen & Beiträge</TabsTrigger><TabsTrigger value="roles">Funktionen & Ehrungen</TabsTrigger><TabsTrigger value="postal">Postanschrift</TabsTrigger><TabsTrigger value="custom">Zusatzfelder</TabsTrigger><TabsTrigger value="privacy">Notizen & DSGVO</TabsTrigger></TabsList>
    <EditorTab value="base"><Field label="Mitgliedsnummer" name="memberNumber" defaultValue={member?.memberNumber} /><Field label="Anrede" name="salutation" defaultValue={member?.salutation} /><Field label="Titel" name="title" defaultValue={member?.title} /><Field label="Vorname" name="firstName" defaultValue={member?.firstName} required /><Field label="Nachname" name="lastName" defaultValue={member?.lastName} required /><SelectField label="Geschlecht" name="gender" defaultValue={member?.gender || ''} options={[['', 'Nicht angegeben'], ['m', 'Männlich'], ['w', 'Weiblich'], ['d', 'Divers']]} /><Field label="Geburtsdatum" name="birthDate" type="date" defaultValue={member?.birthDate} /><Field label="Eintritt" name="entryDate" type="date" defaultValue={member?.entryDate} required /><Field label="Austritt" name="exitDate" type="date" defaultValue={member?.exitDate} /><Field label="Austrittsgrund" name="exitReason" defaultValue={member?.exitReason} /><Field label="Straße" name="street" defaultValue={member?.street} wide /><Field label="PLZ" name="postalCode" defaultValue={member?.postalCode} /><Field label="Ort" name="city" defaultValue={member?.city} /><Field label="Land" name="country" defaultValue={member?.country || 'DE'} /></EditorTab>
    <EditorTab value="contact"><Field label="E-Mail" name="email" type="email" defaultValue={member?.email} wide /><Field label="Telefon privat" name="phonePrivate" defaultValue={member?.phonePrivate} /><Field label="Mobil" name="phoneMobile" defaultValue={member?.phoneMobile} /><Field label="Telefon dienstlich" name="phoneBusiness" defaultValue={member?.phoneBusiness} /><Field label="Homepage" name="website" type="url" defaultValue={member?.website} wide /></EditorTab>
    <EditorTab value="bank"><SelectField label="Zahlart" name="paymentMethod" defaultValue={member?.paymentMethod || 's'} options={[['s', 'SEPA-Lastschrift'], ['r', 'Rechnung'], ['b', 'Bar'], ['l', 'Lastschrift (Altbestand)']]} /><Field label="Kontoinhaber" name="accountHolder" defaultValue={member?.accountHolder} /><Field label="IBAN" name="iban" defaultValue={member?.iban} wide /><Field label="BIC" name="bic" defaultValue={member?.bic} /><Field label="Mandatsreferenz" name="mandateReference" defaultValue={member?.mandateReference} /><Field label="Mandat vom" name="mandateSignedAt" type="date" defaultValue={member?.mandateSignedAt} /><SelectField label="Sequenz" name="sepaSequence" defaultValue={member?.sepaSequence || 'RCUR'} options={[['RCUR', 'Wiederkehrend (RCUR)'], ['FRST', 'Erstmalig (FRST)'], ['OOFF', 'Einmalig (OOFF)'], ['FNAL', 'Letztmalig (FNAL)']]} /></EditorTab>
    <EditorTab value="fees"><Field label="Abteilung" name="department" defaultValue={member?.department || 'Fussball'} /><Field label="Abteilungseintritt" name="departmentEntryDate" type="date" defaultValue={member?.departmentEntryDate || member?.entryDate} /><SelectField label="Beitragsart" name="contributionType" defaultValue={member?.contributionType || contributionTypes[0].name} options={contributionTypes.map((item) => [item.name, `${item.code} · ${item.name}`])} /><Field label="Jahresbeitrag (€)" name="annualFee" type="number" step="0.01" defaultValue={String((member?.annualFeeCents ?? 8000) / 100)} required /><SelectField label="Zahlweise" name="paymentFrequency" defaultValue={member?.paymentFrequency || 'j'} options={[['m', 'Monatlich'], ['v', 'Vierteljährlich'], ['h', 'Halbjährlich'], ['j', 'Jährlich'], ['s', 'Sonderzahlweise']]} /></EditorTab>
    <EditorTab value="roles"><Field label="Funktion" name="functionName" defaultValue={member?.functionName} wide /><Area label="Ehrungen" name="honors" defaultValue={member?.honors} placeholder="Ehrung, Datum und Bemerkung" /></EditorTab>
    <EditorTab value="postal"><Area label="Abweichende Postanschrift" name="alternateAddress" defaultValue={member?.alternateAddress} placeholder="Anrede, Name, Zusatz, Straße, PLZ, Ort, Land" /></EditorTab>
    <EditorTab value="custom"><Area label="Benutzerfelder 01–10" name="customFields" defaultValue={typeof member?.customFields === 'string' ? member.customFields : JSON.stringify(member?.customFields || {}, null, 2)} placeholder={'{\n  "Benutzerfeld_01": "…"\n}'} /></EditorTab>
    <EditorTab value="privacy"><Area label="Notizen und Bemerkungen" name="notes" defaultValue={member?.notes} /><Field label="DSGVO zugestimmt am" name="privacyConsentAt" type="date" defaultValue={member?.privacyConsentAt} /><Check label="E-Mail-Kommunikation erlaubt" name="emailConsent" defaultChecked={member?.emailConsent} /><Check label="Bildverwendung erlaubt" name="imageConsent" defaultChecked={member?.imageConsent} /></EditorTab>
  </Tabs><div className="mt-5 flex justify-end border-t pt-4"><Button disabled={saving} className="bg-[var(--teal)] text-white hover:bg-[var(--teal-dark)]">{saving ? 'Wird gespeichert …' : 'Mitglied speichern'}</Button></div></form></DialogContent></Dialog>;
}

function ContributionsView({ members }: { members: Member[] }) { return <><PageTitle eyebrow="BEITRÄGE" title="Beitragsarten" description="Die im SPG-Bestand gefundenen Jahresbeiträge und ihre Verwendung." /><div className="mt-8 grid gap-4 lg:grid-cols-2">{contributionTypes.map((item) => <div key={item.code} className="flex items-center gap-4 rounded-2xl border border-black/7 bg-white p-5"><div className="grid size-11 place-items-center rounded-xl bg-[var(--sky)] font-mono text-sm font-semibold text-[var(--teal-dark)]">{item.code}</div><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-[var(--muted-ink)]">{members.filter((member) => member.contributionType === item.name && !member.exitDate).length} aktive Zuordnungen</p></div><p className="text-xl font-semibold">{euro(item.amount)}</p></div>)}</div></>; }

function SepaView({ members }: { members: Member[] }) {
  const eligible = members.filter((m) => !m.exitDate && m.paymentMethod === 's' && m.annualFeeCents > 0); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function exportSepa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const response = await fetch('/api/export/sepa', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); if (!response.ok) { const body = await response.json() as { error?: string }; return setError(body.error || 'Export fehlgeschlagen.'); } download(await response.blob(), filename(response, 'SEPA.xml')); setMessage('SEPA-Datei wurde erzeugt.'); }
  return <><PageTitle eyebrow="SEPA-LASTSCHRIFT" title="Lastschriftlauf vorbereiten" description="Vor dem Export werden IBAN, Mandat, Betrag und Vereinsdaten vollständig geprüft." />{(message || error) && <Notice error={error}>{error || message}</Notice>}<div className="mt-8 grid gap-6 xl:grid-cols-[1fr_380px]"><section className="rounded-2xl border border-black/7 bg-white p-6"><h2 className="text-xl font-semibold">Prüfstatus</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><CheckLine label={`${eligible.length} Lastschrift-Mitglieder`} /><CheckLine label="pain.008.001.08 verfügbar" /><CheckLine label="Legacy pain.008.001.02 verfügbar" /><CheckLine label="IBAN-Prüfung vor Export" /></div></section><form onSubmit={exportSepa} className="rounded-2xl bg-[var(--navy)] p-6 text-white"><p className="text-sm text-white/55">EINZUG STARTEN</p><p className="mt-2 text-4xl font-semibold">{eligible.length}</p><div className="mt-6 space-y-4"><DarkField label="Einzugsdatum" name="collectionDate" type="date" required /><SelectField dark label="XML-Format" name="format" defaultValue="pain.008.001.08" options={[['pain.008.001.08', 'Aktuell · pain.008.001.08'], ['pain.008.001.02', 'SPG-Legacy · pain.008.001.02']]} /></div><Button className="mt-5 w-full bg-[var(--mint)] text-[var(--navy)] hover:bg-white"><Download className="mr-2 size-4" />SEPA-XML erzeugen</Button></form></div></>;
}

function SpgView({ members, onImported }: { members: Member[]; onImported: () => Promise<void> }) {
  const [status, setStatus] = useState<BridgeStatus | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function check() { setLoading(true); setError(''); try { const response = await fetch('/api/spg/status'); setStatus(await response.json() as BridgeStatus); } catch { setStatus({ connected: false, compatible: false, reason: 'Status konnte nicht gelesen werden.' }); } finally { setLoading(false); } }
  useEffect(() => { void check(); }, []);
  async function importMembers() { setLoading(true); setError(''); setMessage(''); try { const response = await fetch('/api/spg/import', { method: 'POST' }); const body = await response.json() as { error?: string; imported?: number; updated?: number; skipped?: number }; if (!response.ok) throw new Error(body.error || 'Import fehlgeschlagen.'); await onImported(); setMessage(`${body.imported || 0} Mitglieder neu eingelesen, ${body.updated || 0} aktualisiert, ${body.skipped || 0} lokale Änderungen übersprungen.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Import fehlgeschlagen.'); } finally { setLoading(false); } }
  async function exportBackup() { setLoading(true); setError(''); try { const response = await fetch('/api/export/spg-backup', { method: 'POST' }); if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error || 'Sicherung fehlgeschlagen.'); } download(await response.blob(), filename(response, 'GUT_SPG_Sicherung.zip')); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Sicherung fehlgeschlagen.'); } finally { setLoading(false); } }
  const pending = members.filter((member) => !member.spgSyncedAt).length;
  const canExport = Boolean(status?.compatible && (pending === 0 || status.writeCompatible));
  return <><PageTitle eyebrow="SPG-KOMPATIBILITÄT" title="Manuelle SPG-Übertragung" description="Nur bei Bedarf verbinden: Bestand einlesen oder ZIP mit SQL-Server-.bak, restoreInfo.txt, Vorlagen und Historie erzeugen." />{(error || message) && <Notice error={error}>{error || message}</Notice>}<div className="mt-8 grid gap-6 lg:grid-cols-[1fr_380px]"><section className="rounded-2xl border border-black/7 bg-white p-6"><div className="flex items-start gap-4"><div className="grid size-11 place-items-center rounded-xl bg-[var(--sky)] text-[var(--teal-dark)]"><CloudCog className="size-5" /></div><div><h2 className="text-xl font-semibold">Windows-SPG-Brücke</h2><p className="mt-1 text-sm text-[var(--muted-ink)]">Kein Hintergrund-Sync: Sie wird nur für eine manuell ausgelöste Übertragung gestartet und danach beendet.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><StatusLine ok={Boolean(status?.connected)} label="Brücke momentan erreichbar" /><StatusLine ok={status?.sqlServerMajor === 12} label={`SQL Server ${status?.sqlServerMajor ?? '–'} (erwartet 12)`} /><StatusLine ok={status?.databaseVersion === 782} label={`Datenbankformat ${status?.databaseVersion ?? '–'} (erwartet 782)`} /><StatusLine ok={status?.mandant === 'GUT'} label={`Mandant ${status?.mandant ?? '–'} (erwartet GUT)`} /><StatusLine ok={Boolean(status?.writeCompatible)} label={status?.writeCompatible ? 'SPG-Schreiben freigegeben' : 'SPG-Schreiben gesperrt'} /></div>{status?.reason && <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>Derzeit nicht bereit:</strong> {status.reason}</div>}{pending > 0 && !status?.writeCompatible && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>Schreibfreigabe ausstehend:</strong> {pending} Webapp-Datensätze dürfen erst nach bestandenem SPG-Roundtrip in das ZIP übernommen werden.</div>}</section><aside className={`rounded-2xl p-6 text-white ${canExport ? 'bg-[var(--teal)]' : 'bg-[var(--navy)]'}`}><p className="text-sm text-white/65">MANUELLE ÜBERTRAGUNG</p><p className="mt-3 text-5xl font-semibold">{pending}</p><p className="mt-2 text-sm text-white/70">neue oder geänderte Datensätze</p><Button disabled={!status?.compatible || loading} onClick={importMembers} variant="outline" className="mt-8 h-11 w-full border-white/25 bg-white/10 text-white hover:bg-white/20 hover:text-white"><Download className="mr-2 size-4" />Bestand aus SPG einlesen</Button><Button disabled={!canExport || loading} onClick={exportBackup} className="mt-2 h-11 w-full bg-white text-[var(--navy)] hover:bg-[var(--sky)]"><FileArchive className="mr-2 size-4" />SPG-ZIP erstellen</Button><Button disabled={loading} variant="ghost" onClick={check} className="mt-2 w-full text-white hover:bg-white/10 hover:text-white">Verbindung erneut prüfen</Button></aside></div></>;
}

function SettingsView() {
  const [settings, setSettings] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/settings').then((response) => response.json()).then((data: { settings?: Record<string, string> }) => setSettings(data.settings || {})).catch(() => setError('Einstellungen konnten nicht geladen werden.')); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch('/api/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const body = await response.json() as { error?: string }; if (!response.ok) return setError(body.error || 'Speichern fehlgeschlagen.'); setMessage('Einstellungen gespeichert.'); setError(''); }
  return <><PageTitle eyebrow="EINSTELLUNGEN" title="Verein und SEPA" description="Die Vereins- und Bankdaten für SEPA-Läufe. Geheimnisse bleiben ausschließlich in der Docker-Umgebung." />{(message || error) && <Notice error={error}>{error || message}</Notice>}<form onSubmit={save} className="mt-8 max-w-3xl rounded-2xl border border-black/7 bg-white p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Vereinsname" name="clubName" defaultValue={settings.clubName} wide required /><Field label="Gläubiger-ID" name="creditorId" defaultValue={settings.creditorId} /><Field label="Nachrichtenkürzel" name="sepaMessagePrefix" defaultValue={settings.sepaMessagePrefix || 'GUT-WEB'} /><Field label="Vereins-IBAN" name="iban" defaultValue={settings.iban} wide /><Field label="BIC" name="bic" defaultValue={settings.bic} /></div><Button className="mt-5 bg-[var(--navy)] text-white">Einstellungen speichern</Button></form></>;
}

function EditorTab({ value, children }: { value: string; children: React.ReactNode }) { return <TabsContent value={value}><div className="grid min-h-[340px] gap-4 py-5 sm:grid-cols-2 lg:grid-cols-3">{children}</div></TabsContent>; }
function Field({ label, name, type = 'text', required = false, wide = false, ...props }: { label: string; name: string; type?: string; required?: boolean; wide?: boolean; [key: string]: unknown }) { return <div className={`space-y-2 ${wide ? 'sm:col-span-2' : ''}`}><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} {...props} /></div>; }
function DarkField(props: { label: string; name: string; type?: string; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={props.name} className="text-white/75">{props.label}</Label><Input id={props.name} name={props.name} type={props.type} required={props.required} className="border-white/15 bg-white/10 text-white" /></div>; }
function SelectField({ label, name, options, defaultValue, dark = false }: { label: string; name: string; options: string[][]; defaultValue?: string; dark?: boolean }) { return <div className="space-y-2"><Label htmlFor={name} className={dark ? 'text-white/75' : ''}>{label}</Label><NativeSelect id={name} name={name} className={`w-full ${dark ? 'text-white' : ''}`} defaultValue={defaultValue}>{options.map(([value, title]) => <NativeSelectOption key={value} value={value}>{title}</NativeSelectOption>)}</NativeSelect></div>; }
function Area({ label, name, defaultValue, placeholder }: { label: string; name: string; defaultValue?: string; placeholder?: string }) { return <div className="space-y-2 sm:col-span-2 lg:col-span-3"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} defaultValue={defaultValue} placeholder={placeholder} className="min-h-36" /></div>; }
function Check({ label, name, defaultChecked }: { label: string; name: string; defaultChecked?: boolean }) { return <label className="flex items-center gap-3 rounded-xl border border-black/8 bg-[var(--canvas)] p-4"><input type="checkbox" name={name} defaultChecked={defaultChecked} className="size-4 accent-[var(--teal)]" /><span>{label}</span></label>; }
function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="mb-2 text-sm font-medium tracking-[0.08em] text-[var(--teal-dark)]">{eyebrow}</p><h1>{title}</h1><p className="mt-2 max-w-3xl text-[var(--muted-ink)]">{description}</p></div>; }
function Stat({ label, value, detail, accent = false }: { label: string; value: string; detail: string; accent?: boolean }) { return <div className={`rounded-2xl border p-5 ${accent ? 'border-[var(--navy)] bg-[var(--navy)] text-white' : 'border-black/7 bg-white'}`}><p className={`text-sm ${accent ? 'text-white/60' : 'text-[var(--muted-ink)]'}`}>{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p><p className={`mt-1 text-sm ${accent ? 'text-[var(--mint)]' : 'text-[var(--muted-ink)]'}`}>{detail}</p></div>; }
function CheckLine({ label }: { label: string }) { return <div className="flex items-center gap-2 rounded-xl border border-black/7 px-3 py-3 text-sm"><CheckCircle2 className="size-4 text-[var(--teal)]" />{label}</div>; }
function StatusLine({ ok, label }: { ok: boolean; label: string }) { return <div className="flex items-center gap-2 rounded-xl border border-black/7 px-3 py-3 text-sm">{ok ? <CheckCircle2 className="size-4 text-emerald-600" /> : <AlertCircle className="size-4 text-amber-600" />}{label}</div>; }
function Notice({ error, children }: { error?: string; children: React.ReactNode }) { return <div className={`mb-5 mt-6 flex items-center gap-2 rounded-xl border px-4 py-3 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error ? <AlertCircle className="size-4" /> : <CheckCircle2 className="size-4" />}{children}</div>; }

function memberInput(data: FormData): MemberInput { return { memberNumber: formText(data, 'memberNumber'), salutation: formText(data, 'salutation'), title: formText(data, 'title'), firstName: formText(data, 'firstName'), lastName: formText(data, 'lastName'), gender: formText(data, 'gender'), birthDate: formText(data, 'birthDate'), street: formText(data, 'street'), postalCode: formText(data, 'postalCode'), city: formText(data, 'city'), country: formText(data, 'country'), phonePrivate: formText(data, 'phonePrivate'), phoneMobile: formText(data, 'phoneMobile'), phoneBusiness: formText(data, 'phoneBusiness'), email: formText(data, 'email'), website: formText(data, 'website'), entryDate: formText(data, 'entryDate'), exitDate: formText(data, 'exitDate'), exitReason: formText(data, 'exitReason'), department: formText(data, 'department'), departmentEntryDate: formText(data, 'departmentEntryDate'), contributionType: formText(data, 'contributionType'), annualFeeCents: Math.round(Number(data.get('annualFee')) * 100), paymentFrequency: formText(data, 'paymentFrequency'), paymentMethod: formText(data, 'paymentMethod'), accountHolder: formText(data, 'accountHolder'), iban: formText(data, 'iban'), bic: formText(data, 'bic'), mandateReference: formText(data, 'mandateReference'), mandateSignedAt: formText(data, 'mandateSignedAt'), sepaSequence: formText(data, 'sepaSequence'), functionName: formText(data, 'functionName'), honors: formText(data, 'honors'), alternateAddress: formText(data, 'alternateAddress'), customFields: formText(data, 'customFields'), notes: formText(data, 'notes'), privacyConsentAt: formText(data, 'privacyConsentAt'), imageConsent: data.get('imageConsent') === 'on', emailConsent: data.get('emailConsent') === 'on' }; }
function formText(data: FormData, key: string) { const value = data.get(key); return typeof value === 'string' ? value : ''; }
function initials(member: Member) { return `${member.firstName[0] || ''}${member.lastName[0] || ''}`.toUpperCase(); }
function dateDe(value?: string) { return value ? new Intl.DateTimeFormat('de-DE').format(new Date(`${value}T12:00:00Z`)) : '–'; }
function euro(cents: number) { return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(cents / 100); }
function filename(response: Response, fallback: string) { return response.headers.get('Content-Disposition')?.match(/filename="(.+)"/)?.[1] || fallback; }
function download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
